version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: java
      MYSQL_PASSWORD: java
      MYSQL_DATABASE: coursejdbc
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql